### ISSUE TITLE
qt5 Cyrillic(Russian characters, letters)  Client parse ERROR state=30. 

### ISSUE THREAD

**Issue by TimurAs** [pkoretic/qt-nats#13]
Hello, I found error in client publish method (C++ qt5) when I used Russian letters. So, I also found the answer to solve it. Please, fix it in official version. I just corrected the publish method in  "natsclient.h". Right way is here:

inline void Client::publish(const QString &subject, const QString &message, const QString &inbox)
    {
        QString body = QStringLiteral("PUB ") % subject % " " % inbox % (inbox.isEmpty() ? "" : " ") % QString::number(message.toUtf8().length()) % CLRF % message % CLRF;

        DEBUG("published:" << body);

        m_socket.write(body.toUtf8());
    }

It's forgotten to set Utf8 before setting the length().
Bad way is: 
QString::number(message.length())

Right is:
QString::number(message.toUtf8().length())

**Comment by pkoretic** [comment]
Thanks.
Do you want to push a PR instead so it's your contribution?

**Comment by Flashwalker** [comment]
After system upgrade to qt 5.15.3 on Ubuntu 22.04 i got ugly cyrillic filenames in the left side panel of filepicker dialog:  
![2022-09-13_00-02-11](https://user-images.githubusercontent.com/2188215/191389285-f1be77fc-fc2e-4d90-a427-ff93031cc8bf.jpg)
