### ISSUE TITLE
I am newbie , How to install Qt5 in Visual Studio 2017

### ISSUE THREAD

**Issue by NantipatSoftEn** [pkoretic/qt-nats#14]
I try to install   nl.cqm.Qt5Core on Nuget packages manager 

 `https://www.nuget.org/packages/nl.cqm.Qt5Core/5.9.6/`

but  don't have file  QSslConfiguration.h and QSslSocket.h  in natsclient.h 
`
#include <QSslConfiguration.h>
#include <QSslSocket.h>
`

**Comment by pkoretic** [comment]
It seems that package doesn't enable SSL so I guess you cannot use it
if you would like to use it without SSL you can easily comment out the includes
