### ISSUE TITLE
Question(s) & thanks

### ISSUE THREAD

**Issue by ghost** [pkoretic/qt-nats#15]
Hi,

By glancing at the sources I noticed that **qt-nats** has no cluster awareness like the official Synadia C client (no server list, no automatic reconnects etc). 

Form [nats.c](https://github.com/nats-io/nats.c#build), **Clustered usage**:

```
static char *servers[] = { "nats://localhost:1222",
                           "nats://localhost:1223",
                           "nats://localhost:1224"};
                           
// Setup options to include all servers in the cluster.
// We first created an options object, and pass the list of servers, specifying
// the number of servers on that list.
natsOptions_SetServers(opts, servers, 3);

// We could also set the amount to sleep between each reconnect attempt (expressed in
// milliseconds), and the number of reconnect attempts.
natsOptions_SetMaxReconnect(opts, 5);
natsOptions_SetReconnectWait(opts, 2000);

// We could also disable the randomization of the server pool
natsOptions_SetNoRandomize(opts, true);

// Setup a callback to be notified on disconnects...
natsOptions_SetDisconnectedCB(opts, disconnectedCb, NULL);

// And on reconncet
natsOptions_SetReconnectedCB(opts, reconnectedCb, NULL);

// This callback could be used to see who we are connected to on reconnect
static void
reconnectedCb(natsConnection *nc, void *closure)
{
    // Define a buffer to receive the url
    char buffer[64];

    buffer[0] = '\0';

    natsConnection_GetConnectedUrl(nc, buffer, sizeof(buffer));
    printf("Got reconnected to: %s\n", buffer);
}
```

This prompted me to ask:

a) How compatible is **nats-qt** with current **nats-server** versions (eg. v2.0.4) ?
b) Would @pkoretic be willing to add the missing functionality to **qt-nats**?

Anyway, thank you for sharing the code. Great little lib!

**Comment by pkoretic** [comment]
Hi @ncg81!

Thanks for the message. To be honest I have to take a look at 2.0.4 version to see what is missing now. Cluster support seems easy enough but seems there are more changes overall that should be added although not that many.

Best regards,
Petar

**Comment by ghost** [comment]
Hi Petar!

Thank you far looking into this. I think adding cluster awareness to **qt-nats** would make the client a natural choice for production grade Qt based applications.

Since I'm months away from release I will plug **qt-nats** in my application and start developing around it right away. The current version has everything needed for a dev environment.
