### ISSUE TITLE
Fix for ambiguous Error using Qt 5.8

### ISSUE THREAD

**Issue by MJPees** [pkoretic/qt-nats#2]
natsclient.h:466: Fehler: call of overloaded 'compare(const char [5], Qt::CaseSensitivity)' is ambiguous
             if(operation.compare("PING", Qt::CaseInsensitive) == 0)
                                                             ^

![image](https://cloud.githubusercontent.com/assets/22058666/22269872/7e198c60-e28d-11e6-9073-07a1b6a32178.png)

**Comment by pkoretic** [comment]
Thanks. I'll switch that over to QStringLiteral while I'm at it
