### ISSUE TITLE
Wrong Message length- missing toUtf8()

### ISSUE THREAD

**Issue by MJPees** [pkoretic/qt-nats#3]
Should be:

            if(current_pos + message_len + CLRF.length() > buffer.toUtf8().length())
            {
                DEBUG("message not in buffer, waiting");
                break;
            }

**Comment by pkoretic** [comment]
@MJPees thanks! I'll fix it asap!

**Comment by MJPees** [comment]
another length bug:

while(last_pos != buffer.toUtf8().length())
        {

            // we always get delimited message
            current_pos = buffer.indexOf(CLRF, last_pos);
            if(current_pos == -1)
            {
                qCritical() << "CLRF not found, should not happen";
                break;
            }
